import "./globals.css";
import { Inter, Baskervville } from "next/font/google";
import { AuthProvider } from "./context/AuthContext";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import AddBar from "@/components/AddBar";
import NewHeader from "@/components/NewHeader";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-body",
  display: "swap",
});

const baskervville = Baskervville({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-basker",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${baskervville.variable} antialiased`}
      >
        <AuthProvider>
          {/* <AddBar /> */}
          {/* <Header /> */}
          <NewHeader />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
